// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Entities;

public partial class Exam
{
    public Guid Id { get; set; }

    public string Title { get; set; }

    public int DurationInMinutes { get; set; }

    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();

    public virtual ICollection<Submission> Submissions { get; set; } = new List<Submission>();
}