// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Entities;

public partial class ExamQuestion
{
    public Guid ExamId { get; set; }

    public Guid QuestionId { get; set; }

    public int Order { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual Question Question { get; set; }
}