// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Entities;

public partial class ExamSet
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public Guid FlashcardId { get; set; }
}