// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Entities;

public partial class Question
{
    public Guid Id { get; set; }

    public string QuestionText { get; set; }

    public string QuestionType { get; set; }

    public Guid QuestionBankId { get; set; }

    public string CorrectAnswer { get; set; }

    public virtual ICollection<ExamQuestion> ExamQuestions { get; set; } = new List<ExamQuestion>();

    public virtual QuestionBank QuestionBank { get; set; }

    public virtual ICollection<SubmissionAnswer> SubmissionAnswers { get; set; } = new List<SubmissionAnswer>();
}