// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Entities;

public partial class SubmissionAnswer
{
    public Guid Id { get; set; }

    public Guid SubmissionId { get; set; }

    public Guid QuestionId { get; set; }

    public string SelectedAnswer { get; set; }

    public bool IsCorrect { get; set; }

    public virtual Question Question { get; set; }

    public virtual Submission Submission { get; set; }
}