// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BO.Entities;

public partial class Submission
{
    public Guid Id { get; set; }

    public Guid ExamId { get; set; }

    public Guid StudentId { get; set; }

    public DateTime StartedAt { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public double? Score { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual ICollection<SubmissionAnswer> SubmissionAnswers { get; set; } = new List<SubmissionAnswer>();
}